spring.application.name=api-gateway

server.port=8080

# =========================
# PATIENT + MEDICAL RECORD
# =========================

spring.cloud.gateway.routes[0].id=patient-medicalrecord-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/patients/**,/medical-records/**

# =========================
# DOCTOR SERVICE
# =========================

spring.cloud.gateway.routes[1].id=doctor-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/doctors/**,/schedules/**,/specializations/**

# =========================
# APPOINTMENT SERVICE
# =========================

spring.cloud.gateway.routes[2].id=appointment-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/appointments/**

# =========================
# USER + NOTIFICATION
# =========================

spring.cloud.gateway.routes[3].id=user-notification-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/users/**,/notifications/**

# =========================
# EXPORT + STATISTICS
# =========================

spring.cloud.gateway.routes[4].id=statistics-export-service
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/export/**,/statistics/**

# =========================
# REACT CORS
# =========================

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true