spring.application.name=user-notification-service

server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/user_notification_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tautandreea36@gmail.com
spring.mail.password=drneyunhcmvoyngs


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# TWILIO
twilio.account.sid=AC22baae886c8fa447eac7023a53c7662d
twilio.auth.token=d8d63d24d3a5b476a2bd00d1fa1436af
twilio.phone.number=+16672601184